# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    app.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }
        #arguments: ['@app.markdown_transformer']
        autowire: true

    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags:
            - { name: form.type }

    app.redirect_after_registration_subscriber:
        class: AppBundle\EventListener\RedirectAfterRegistrationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
